### ISSUE TITLE
Lights Out Crash

### ISSUE THREAD

**Issue by gamerCat898** [Cairath/ONI-Mods#145]
**Describe the bug**
When you Attempt to play with the Lights Out mod enabled, the game crashes once you unpause.

**To Reproduce**
1. Enable the Lights Out mod.
2. Restart the game.
3. Load (or create?) a save.
4. Unpause.
5. Error.

**Expected behavior**
Game should play w/out issue.

**Output log**
MissingMethodException: !4 StateMachine`4/Parameter`1.Set(!4,!1)

BucketUpdater`1[DataType].Update (DataType data, System.Single dt) (at <1b5c2ff4f53d4a48b7159ed84d905978>:0)
UpdateBucketWithUpdater`1[DataType].Update (System.Single dt) (at <1b5c2ff4f53d4a48b7159ed84d905978>:0)
StateMachineUpdater+BucketGroup.AdvanceOneSubTick (System.Single dt) (at <1b5c2ff4f53d4a48b7159ed84d905978>:0)
StateMachineUpdater.AdvanceOneSimSubTick () (at <1b5c2ff4f53d4a48b7159ed84d905978>:0)
Game.SimEveryTick (System.Single dt) (at <cb20703507b14eea8088dbc44abf7f85>:0)
Game.Update () (at <cb20703507b14eea8088dbc44abf7f85>:0)

Build: U43-526233-S

**Comment by Fenix1782** [comment]
It is due to the last ONI update, only way to make game work with Lights Out enabled is pass to previous update steam branch
[](https://forums.kleientertainment.com/forums/topic/140474-previous-update-steam-branch-access/)

Since Lights Out author seem really absent i guess we'll have to stop using it as soon as Klei decide to close the "grace period"

**Comment by Cairath** [comment]
I am so absent that a few hours ago I responded to another issue that I am aware of the update and I'll be updating mods within a few days... I don't have time to respond to every single ticket, I'd rather spend that time actually fixing things.

**Comment by Cairath** [comment]
Yes, thank you for the report, maaaany mods broke this update so I'm taking the time to make sure all (over 30) work fine :)

**Comment by Fenix1782** [comment]
Oh sorry m8! searched couple days ago, when crash first happened, but didn't find any sign of you in ONI threads, must be my fault!

**Comment by Cairath** [comment]
I only lurk the forums, but I'm very active on the ONI discord!

**Comment by Tellik** [comment]
> Since Lights Out author seem really absent i guess we'll have to stop using it as soon as Klei decide to close the "grace period"

It might be that you probably didn't mean to come off sounding like it, but it really sounds really impatient/passive aggressive like you're blaming the mod author. 

I don't expect them to respond, or tell everyone that they're working on it. Hell, I'm surprised half the time when they do push out updates or still maintain these mods. All of which they do for free on their personal time. Best I can do is provide as much detailed feedback as I can to make their jobs easier. 

... especially when they have over 30 mods they're maintaining.

**Comment by TroublesomeCorvid** [comment]
Guys, got a work-around for this!

Lights Out ONLY crashes the game the instant a brand new map is started.  I have no idea why.  That said, I have verified that this is a viable work around:

1) Prior to starting a new map, deactivate the Lights Out mod.
2) After restarting ONI, generate your new map.
3) Once the new map has been generated and the first autosave has been created, quit to Main Menu and reactivate the Lights Out mod.
4) After ONI restarts, click the Resume Game button.
5) The previously generated map should load just fine, with the message that the mod, Lights Out, is NOT DISABLED.

Have fun, guys.

Cairath, I hope this helps in some way.

**Comment by gamerCat898** [comment]
I've tested TroublesomeCorvid's workaround, and it appears that they forgot that the triggering condition for the crash is the simulation running w/ Lights out active, as it crashed the same way it always has whenever I tried to use the mod.

**Comment by gamerCat898** [comment]
I've just now found that the crash happens with or without the visual effects active.

**Comment by Evil2056** [comment]
![20221017173349_1](https://user-images.githubusercontent.com/115745235/196296354-99710d92-1934-435d-a809-7de57dcf7bce.jpg)

**Comment by Evil2056** [comment]
I got that far into the game before it crashes

**Comment by gamerCat898** [comment]
seems about right

**Comment by TheEdster3** [comment]
Seems to crash during the update function in LightsOutMonitor as the stack trace showed. 

<img width="382" alt="image" src="https://user-images.githubusercontent.com/11467380/196319022-bd3d5bde-18a6-468b-8c33-fdef882b1574.png">

I know nothing about modding ONI, I'm assuming there's been some change in what some ONI specific function expects with the recent update and it's complaining/crashing because of it. 

Try Catching the update function actually allows the mod to work but with horrible performance issues. (As one would expect since it's constantly spamming out exceptions.) 

Similarly, removing the update function allows the rest of the mod to work but the lighting status of any given dupe is never updated (Also as one would expect.) 

Wanted to try and fix this but don't have the time unfortunately. This info is probably really obvious, but I'm really interested in trying this mod out and wanted to help in any way I can!

**Comment by Cairath** [comment]
Guys, I don't need help, especially with the coding part. Nor do I want it. I wanted to make some performance improvements so it's waiting for a bit. It's going to be done when its done.

**Comment by TheEdster3** [comment]
Sorry, didn't mean to frustrate you. :(

**Comment by TheEdster3** [comment]
Sorry @Cairath, didn't mean to imply a rush or to overstep my bounds. I'm sure it must be frustrating getting a bajillion comments/requests when you're just trying to do your thing. Hope all is well.
