### ISSUE TITLE
Github error!

### ISSUE THREAD

**Issue by MetaStazz** [Cairath/ONI-Mods#153]
Your mod list is missing some mods.
Your released zip is missing some mods.
Some of your mods doesn't have the same folder name and are a pain to find !! (Which one is Flow Splitters for example)

**Comment by Cairath** [comment]
Steam is the source that I keep up to date. GitHub is mostly for me and i don't push all updates here immediately. It also contains unreleased mods or mods i no longer maintain and those were taken off steam. The zip is currently out of date after most recent updates (i can update it later today), and the folder names won't be changed either since it's an automated solution using internal names that's meant to be used only when steam acts up. You can see update dates on steam.
