### ISSUE TITLE
You should mark some of your mods as deprecated on steam

### ISSUE THREAD

**Issue by NastyFlytrap** [Cairath/ONI-Mods#174]
For example, the geyser calculated average output mod has been implemented into the game years ago. Please put [obsolete] or [deprecated] into its title.

Thank you

**Comment by Cairath** [comment]
It was hardly "years ago" and you can just not install it.

**Comment by NastyFlytrap** [comment]
> It was hardly "years ago" and you can just not install it.

I could, but if im just on the workshop im not going to know that its been put into the game. Which is why you should tag it as such.

Also, since you're here, i have a second gripe. I have a save file i'd like to use but it was using achievement progress and i dont have that mod anymore. I cant even install the mod because your other solution to deal with deprecated mods is to private them, so now my savefile is permanently locked because of that. I'd appreciate it if you helped me with that

**Comment by Cairath** [comment]
The mod was safe to remove from saves - 99% if not all of my mods are - are you getting an error trying to launch that save? If so, please send the full log to me -it shouldn't be happening

**Comment by NastyFlytrap** [comment]
I was hoping aswell that it'd be safe to remove, since it doesnt add an actual object to the game, but this is the one i guessed to be the culprit. 

The three other candidates are, 
https://steamcommunity.com/sharedfiles/filedetails/?id=2191194318 Cant turn it on because its outdated, probably using old harmony
https://steamcommunity.com/sharedfiles/filedetails/?id=1715248368 Crashes game on launch 
https://steamcommunity.com/sharedfiles/filedetails/?id=1735550356 Outdated again

My other guess would be #2 the wheezeworts, because it may be adding a different object and replacing the vanilla wheeze
wort with that. Or the self sealing airlocks for the same reason of replacing airlocks with same looking different objects
[Player.log](https://github.com/Cairath/ONI-Mods/files/12586026/Player.log)

**Comment by Cairath** [comment]
This is the actual error:

NullReferenceException: Object reference not set to an instance of an object
  at KBatchedAnimUpdater.OnMovementStateChanged (UnityEngine.Transform transform, System.Boolean is_moving) [0x00011] in <ad882e55d8ac49379773540ee16f428f>:0 
  at CellChangeMonitor.RunMovementStateChangedCallbacks (System.Int32 instance_id, System.Boolean state) [0x00058] in <d2ff0ec32ae74bb091b2c7c87705ee3b>:0 
  at CellChangeMonitor.RenderEveryTick () [0x00187] in <d2ff0ec32ae74bb091b2c7c87705ee3b>:0 
  at Game.Update () [0x0007d] in <ad882e55d8ac49379773540ee16f428f>:0 


Mods that add new buildings are the ones that remove gracefully, it's editing existing things that is more prone to crashing saves. 
Either way -this crash is definitely not because of achievement progress missing - I'd try disabling more mods though, most likely it's one of the ones you have active

**Comment by NastyFlytrap** [comment]
> This is the actual error:
> 
> NullReferenceException: Object reference not set to an instance of an object at KBatchedAnimUpdater.OnMovementStateChanged (UnityEngine.Transform transform, System.Boolean is_moving) [0x00011] in :0 at CellChangeMonitor.RunMovementStateChangedCallbacks (System.Int32 instance_id, System.Boolean state) [0x00058] in :0 at CellChangeMonitor.RenderEveryTick () [0x00187] in :0 at Game.Update () [0x0007d] in :0
> 
> Mods that add new buildings are the ones that remove gracefully, it's editing existing things that is more prone to crashing saves. Either way -this crash is definitely not because of achievement progress missing - I'd try disabling more mods though, most likely it's one of the ones you have active

I tried without a single mod and got the same error message, which is why i suspected leftover modded objects
