### ISSUE TITLE
Drywall also Hiding plants

### ISSUE THREAD

**Issue by Gfurst** [Cairath/ONI-Mods#4]
When using the `drywall hides pipes` mod it will also end up hiding plants, which I'm assuming is not intended.

**Comment by Cairath** [comment]
Hey,

The scene layers in the game are wonky and even though the wall layer is supposed to be behind the plant layer, the game often messes it up. Please take a look at the DrywallAndTempshiftHidePipesSeparateObjects mod (https://github.com/Cairath/ONI-Mods/blob/master/modfiles/DrywallAndTempshiftHidePipesSeparateObjects.dll) which leaves the original walls in tact and adds objects "Drywall (hides pipes)" and "Tempshift plate (hides pipes)" so that you can use those where you need to cover things up, and the normal wall elsewhere! 

I will most likely remove the original DrywallHidesPipes to avoid confusion

**Comment by Cairath** [comment]
Removed the deprecated mod.
