### ISSUE TITLE
Make the Flow splitter more mathematically correct

### ISSUE THREAD

**Issue by Sijko** [Cairath/ONI-Mods#6]
**Is your feature request related to a problem? Please describe.**
flow splitter uneven division

**Describe the solution you'd like**
Can you rewrite the mod so when there's more than 10K for water and 1K for gas in the pipe than it divides it evenly too, not like now - def max to 1 pipe, all the rest to another :))))))

**Describe alternatives you've considered**
There are no alternatives (c) Reapers

**Additional context**
dads ol

**Comment by Cairath** [comment]
It does split it evenly though, whether it's full or not

https://puu.sh/BE3dj/79fdc62874.png

There can't be more than 10kg/1kg in the pipe, unless you're using mods that mess with that? If so, they should modify the field that describes max flow in the pipe globally, since this mod uses that to check how much a pipe can fit.

**Comment by Cairath** [comment]
Mod-friendlier in b60a23f
